#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
This script illustrates the Top-Down Sequence.

@author: Michael Bergman
"""

import numpy as np
import pandas
import statsmodels.api as sm
import scipy.stats as stats
import math

import statsmodels.tsa.vector_ar.var_model
#import statsmodels.tsa.vector_ar.util

from statsmodels.tsa.vector_ar.var_model import *
from numpy.linalg import *
from statsmodels.tsa.api import *
from scipy.stats import chi2
from tabulate import tabulate
from statsmodels.regression.linear_model import (
    GLS,
    OLS,
    WLS,
    burg,
    yule_walker,
)
#from statsmodels.tsa.vector_ar import *
#from statsmodels.tsa.vector_ar import util
import statsmodels.base.wrapper as wrap
from statsmodels.iolib.table import SimpleTable
from statsmodels.tools.decorators import cache_readonly, deprecated_alias
from statsmodels.tools.linalg import logdet_symm
from statsmodels.tools.sm_exceptions import OutputWarning
from statsmodels.tools.validation import array_like
from statsmodels.tsa.base.tsa_model import (
    TimeSeriesModel,
    TimeSeriesResultsWrapper,
)
import statsmodels.tsa.tsatools as tsa
from statsmodels.tsa.tsatools import duplication_matrix, unvec, vec
from statsmodels.tsa.vector_ar import output, plotting, util
from statsmodels.tsa.vector_ar.hypothesis_test_results import (
    CausalityTestResults,
    NormalityTestResults,
    WhitenessTestResults,
)
from statsmodels.tsa.vector_ar.irf import IRAnalysis
from statsmodels.tsa.vector_ar.output import VARSummary
from statsmodels.tsa.vector_ar.var_model import *

from Ownfunctions import *


import matplotlib.pyplot as plt

data = pandas.read_excel("BlanchardQuah.xlsx")
data = data[['dy','u']]

# Add dates to DataFrame
dates = pandas.date_range(start='1948-04-01', end='1988-01-01', freq='QE')
data.index = pandas.DatetimeIndex(dates)

# Determine lag order using information criteria
model = VAR(data)
pmax = 12
lagorderres = model.select_order(pmax)
print(lagorderres.summary())

# Lag order and # of equations
p = 2
K = 2

# Define VAR model, estimate model and show estimates

results = model.fit(p)
print(results.summary())
# Plot the data
results.plot()

# Use statsmodels tests for normality and autocorrelation
print(results.test_normality().summary())
print(results.test_whiteness().summary())
print(results.test_causality('dy', 'u', kind='f').summary())

# Instead, use own functions to test for Autocorrelation, normality and ARCH

# First create an array with residuals generated by VAR estimation
resid = pandas.DataFrame(results.resid).to_numpy()

# Univariate tests for autocorrelation, ARCH and normality
bglag = 6
archlag = 4
ddof = results.df_model
owndiag(resid,K,ddof,bglag,archlag)

# Check stability using own function

# First we need the coefficients associated with lagged endogenous variables
coefs = pandas.DataFrame(results.params).to_numpy()
# Then delete coefficients associated with deterministic components
coefs = np.delete(coefs,0,axis=0)
# Finally transpose
coefs = coefs.transpose()

# Now we first compute the companion matrix
A = companion(coefs)
# and then we compute and print the modulus
stabVAR(A)

# print sigma and cholesky decomposition

print(results.sigma_u)
print(cholesky(results.sigma_u))